Develop
msiarko/ReadingList pull request #1
Opened 2018-06-03 14:47 UTC by MikhailSiarko

Features:
- Register/Login users;
- Add, remove, edit book list items;
- Edit book list;
- Reding time tracking.

2018-06-20 14:15 UTC, KatzuoOgust requested changes

2018-06-20 14:15 UTC, KatzuoOgust commented on ReadingList.Domain/DTO/BookList/SharedBookListDto.cs
> +        [JsonIgnore]
add new line between props

2018-06-20 14:15 UTC, KatzuoOgust commented on ReadingList.Domain/MapperProfiles/BookListProfile.cs
> +                    })))).ReverseMap().ConvertUsing<BookListConverter>();
chop line by dots as hard to see what is for what:
```cs
CreateMap<SharedBookListDto, BookList>()
	.ForMember(d => d.JsonFields,
		m => m.MapFrom(
			b => JObject.FromObject(b, JsonSerializer.Create(new JsonSerializerSettings
				{
					Formatting = Formatting.Indented
				}))))
	.ReverseMap()
	.ConvertUsing<BookListConverter>();
```

2018-06-20 14:15 UTC, Happi-cat commented on ReadingList.Domain/Services/Encryption/DefaultEncryptionAlgorithm.cs
> +        public string Execute(string normalString) => _algorithm(normalString);
why not to move lambda body as method body to that method?

2018-06-20 14:15 UTC, Happi-cat commented on ReadingList.Domain/Services/ReadingTimeCalculator.cs
> +                    diff = TimeSpan.FromTicks(DateTime.Now.Ticks - previousDate.Ticks);
No need to get ticks, just do: `diff = DateTime.Now - previousDate`

2018-06-20 14:15 UTC, Happi-cat commented on ReadingList.Domain/Services/Sql/Implementations/UserSqlService.cs
> +        public string GetUserByLoginSql(string parameterName = "login") =>
not sure that `parameterName` is a right name for argument  
can be named as login
and what was the intention to defined default value `login`?

2018-06-20 14:15 UTC, Happi-cat commented on ReadingList.Domain/Services/Sql/Implementations/UserSqlService.cs
> +            _sqlBuilder.Where($"Login = @{parameterName}").ToSql();
potential place for SQL injection

2018-06-22 13:52 UTC, KatzuoOgust requested changes

2018-06-22 13:52 UTC, Happi-cat commented on ReadingList.Api/Controllers/AccountController.cs
> +            if (!result.IsSucceed)
Code was repeated several times so can be moved into separate method so will look like (just an example):
```cs
return AskResult(result);
```

2018-06-29 07:01 UTC, KatzuoOgust requested changes

2018-06-29 07:01 UTC, Happi-cat commented on ReadingList.Api/ExceptionToStatusCodeProvider.cs
> +            }
`while(true)` лучше юзать когда ты реально НЕ знаешь основное условие выхода
тут же можно юзать `exceptionType.IsSubclassOf(_baseCaseExceptionType)`
читая же код с `while(true)` начинаешь думать что цикл может быть бесконечным когда это не так
```cs
while(exceptionType.IsSubclassOf(_baseCaseExceptionType)) 
{

}
return HttpStatusCode.InternalServerError;
```

2018-06-29 07:01 UTC, Happi-cat commented on ReadingList.Api/ExceptionToStatusCodeProvider.cs
> +                    (p, c) => c).Distinct(new KeyValueEqualityComparer()).ToDictionary(pair => pair.Key, pair => pair.Value);
если вдруг появляется перенос аргумента на новую строку то и цепочку вызовов лучше разносить на новые строки для повышения читабельности иначе с ходу не понятно кто за кем чейнится и чейнимся ли мы на результат или какой-то аргумент

2018-06-29 07:01 UTC, Happi-cat commented on ReadingList.Api/ExceptionToStatusCodeProvider.cs
> +            _source = InitializeExceptionToStatusCodeMap(map);
т.к. внутри метода инициализациия содается новый словарь то нет смысла делать аргумент столь конкретным и можно указать, например, тип IReadOnlyDictionary

2018-06-29 07:01 UTC, Happi-cat commented on ReadingList.Api/Middlewares/ExceptionHandlingMiddleware.cs
> +        public async Task InvokeAsync(HttpContext context, ExceptionToStatusCodeProvider exceptionToStatusCodeProvider)
`ExceptionToStatusCodeProvider ` в данном случае лучше будет передавать не в `InvokeAsync` метод а в конструктор, т.е. в момент `app.UseMiddleware`

2018-06-29 07:01 UTC, Happi-cat commented on ReadingList.Api/Middlewares/ExceptionHandlingMiddleware.cs
> +            catch (Exception e)
ловить все Exception-ы не очень ибо в случае тасков и асинк кода
при канселейшне может быть выкинут `OperationCanceledException` ([link](https://msdn.microsoft.com/ru-ru/library/system.threading.cancellationtoken.throwifcancellationrequested(v=vs.110).aspx)) на который скорее всего ответить не сможешь либо нет смысла

2018-06-29 07:01 UTC, Happi-cat commented on ReadingList.Client/src/components/NavBar/NavBar.tsx
> +    const navLinks = props.links.map((value, index) => {
а можно return в лямбде опустить и записать чуть проще

2018-06-29 07:01 UTC, Happi-cat commented on ReadingList.Client/src/components/NavBar/NavBarLink/NavBarLink.tsx
> +        ? (<a className={props.className} onClick={props.link.action}>{props.link.text}</a>)
большая тернарка: либо меняем тернарку на if else либо делаем частные методы рендеринга
`const link = props.link.action ? renderA() : renderB();`

2018-06-29 07:01 UTC, Happi-cat commented on ReadingList.Client/src/components/NavBar/NavBarLink/NavBarLink.tsx
> +                        to={props.link.href}>
в ряде реакт гайдов можно встретить совет касающийся стилистики кода:
 если вдруг мы передаем какие-то пропы и вынуждены переносить то лучше переносить каждый проп
```jsx
<NavLink
  className={props.className}
  activeClassName={props.activeClassName}
  to={props.link.href}
>
  {content}
</NavLink>
```

2018-06-29 07:01 UTC, Happi-cat commented on ReadingList.Client/src/components/PrivateBookLI/PrivateBookLI.tsx
> +                    <input type="hidden" name="item-id" value={props.listItem.id} />
для большей наглядности можно делать при необходимости локальные Footer,Header,TitleEdit и прочие компоненты либо юзать renderSmth методы

2018-06-29 07:01 UTC, Happi-cat commented on ReadingList.Client/src/containers/Account/Account.tsx
> +        if(confirmPassword === null) {
эта логика могла бы быть внутри `AccountForm` где она и должна быть.
сейчас получается что `Account` знает про некоторое устройство иных компонент.
onSubmit имел бы примерно такую сигнатуру:
`({ emaill: string, password: string, confirmPassword: bool }) : void`

2018-06-29 07:01 UTC, Happi-cat commented on ReadingList.Client/src/containers/PrivateBookList/PrivateBookList.tsx
> +                    this.props.bookList && !this.props.bookList.isInEditMode
в JSX сложные условия лучше выносить в `const` / `var` переменные либо можно даже в геттеры для читабельности.
конкретный случай можно оставить как есть

2018-07-20 14:27 UTC, KatzuoOgust requested changes

2018-07-20 14:27 UTC, KatzuoOgust commented on ReadingList.Api/Abstractions/BaseController.cs
> +            _mediator = MediatorContainer.GetMediator();
почему решил использовать servicelocator подход для получения инстанса медиатора вместо DI через конструктор?

2018-07-20 14:27 UTC, KatzuoOgust commented on ReadingList.Api/Controllers/AccountController.cs
> +        [ValidateModelState]
учитывая что эта проверка навешена на каждый экшон контроллера то можно мувнуть на уровень контроллера(т.е. класса)

2018-07-20 14:27 UTC, KatzuoOgust commented on ReadingList.Api/Controllers/PrivateListController.cs
> +        public async Task<IActionResult> Put([FromRoute] int id, [FromBody] UpdatePrivateListItemData updatePrivateListItemData)
а не лучше ли разграничить два метода Put по названию а не по аргументам
один оставив как Put (продразумеватся Put Private List) 
а второй превратив в UpdateItem или поднобным образом?

2018-07-20 14:27 UTC, KatzuoOgust commented on ReadingList.Api/ExceptionToStatusCodeProvider.cs
> +                map.SelectMany(pair => pair.Value
а почему используешь  `SelectMany` с collection & result селекторами если вроде как достаточно использовать с просто селектором
```cs
  map.SelectMany(pair => pair.Value.Select(t => new KeyValuePair<Type, HttpStatusCode>(t, pair.Key)))
                    .Distinct(new KeyValueEqualityComparer())
                    .ToDictionary(pair => pair.Key, pair => pair.Value);
```

2018-07-20 14:27 UTC, KatzuoOgust commented on ReadingList.Domain/Services/Validation/OnNotExistExceptionData.cs
> +    public class OnNotExistExceptionData
можно сделать чайлд класс:
OnNotExistExceptionData<T>
и убрать `typeof(PrivateBookListItemWm).Name,` при вызове конструктора ибо вытянется из typeof(T).Name

2018-07-20 14:27 UTC, KatzuoOgust commented on ReadingList.Domain/Services/Validation/OnNotExistExceptionData.cs
> +            get
учитывая что Params делает вызов рефлексии (тяжеловат в выполнении) лучше сделать его в виде метода
GetParams дабы подчеркнуть что он computed

2018-07-20 14:27 UTC, KatzuoOgust commented on ReadingList.ReadModel/DbConnection/IReadDbConnection.cs
> +        Task<TR> QuerySingleAsync<TP, TS, TR>(string query, Func<TP, TS, TR> map, object param = null);
TP, TS, TR - не самые описательные имена что есть что и должны быть полными, например TSource, TResult

2018-07-20 14:27 UTC, KatzuoOgust commented on ReadingList.Tests/ExceptionToStatusCodeMapTests.cs
> +        public void MapNullReferenceExceptionType()
названия методов в тестах могут использовать нейминг гайдлайны отличные от стандартных
ибо имена могут быть многословны т.к. должны описывать кейс.
вот ряд примеров:
`<Method>_<ExpectedResult>_<Condition>`
`Map_ReturnsAbc_WhenXyzPassed`
`Map_ReturnsAbc123_WhenXyzAns0Passed`
`map_returns_smth_when_smth`

2018-07-20 14:27 UTC, KatzuoOgust commented on ReadingList.Domain/Infrastructure/Extensions/UpdateEntityExtension.cs
> +            var entityProperties = entity.GetType().GetProperties(BindingFlags.Public | BindingFlags.Instance);
учитывая что Enitiy не так и много то это дело можно и закешить/заюзать скомпиленные экспрешоны 
ибо рефлекшон не так быстр (пока что)

2018-07-20 14:27 UTC, KatzuoOgust commented on ReadingList.Domain/CommandHandlers/PrivateList/UpdatePrivateListItemCommandHandler.cs
> +            EntitiesValidator.Validate(item,
поидее можно было бы просто юзать throw new ObjectNotExistException как и было
не совсем понимаю почему не делать формирование месседжа в самом эксепшоне а ключ передавать в виде объекта/словаря и сериализовать в JSON к примеру

[ArgumentException для размышлений](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/ArgumentException.cs)

2018-07-20 14:27 UTC, KatzuoOgust commented on ReadingList.Client/src/index.tsx
> +      <ConnectedRouter history={history}>
отступ великоват

2018-07-20 19:27 UTC, msiarko commented on ReadingList.Api/Abstractions/BaseController.cs
> +            _mediator = MediatorContainer.GetMediator();
чтобы не создавать одинаковые конструкторы в классах наследниках, ибо по замыслу контроллеры будут использовать только медиатор для взаимодействия с доменной логикой

2018-07-27 14:48 UTC, MikhailSiarko commented on ReadingList.Api/ExceptionToStatusCodeProvider.cs
> +                map.SelectMany(pair => pair.Value
Исправлено

2018-08-13 11:52 UTC, KatzuoOgust requested changes

2018-08-13 11:52 UTC, Happi-cat commented on ReadingList.Domain/Services/EntityUpdate/EntityUpdateService.cs
> +            if (_cache.ContainsKey(typeof(TEntity)))
EntityUpdateService  - зареген как синглтон 
а доступ к кешу не thread-safe 
можно заюзать ConcurrentDictionary

2018-08-13 11:52 UTC, Happi-cat commented on ReadingList.Domain/Services/EntityUpdate/EntityUpdateService.cs
> +                                Expression.Call(property, _setValueMethodInfo, entityParameter, value))),
все равно юзаешь рефлексию в скомпиленном экспрешоне,
у Call сигнатура подсказывает: `Expression.Call(Expression instance, MethodInfo, method, ...)`
что ты вызываешь метод инстанса т.е. что-то вроде `property.SetValue(...)`

должно быть что-то вроде такого :

```cs
var propertyExpression = Expression.PropertyOrField(entityParameter, property.Name);
Expression.Assign(
  propertyExpression, 
  Expression.Call(_getValueOrDefaultMethodInfo, sourceParameter, Expression.Property(property, "Name"))
)
```

пересмотри создание апдейтера, кмк он должен выглядеть так:
ты указываешь TEntity а билдер достает все пропы
затем фильтрует и оставляет те которые моджно сетать
и на основе этого списка строит блок экспрешон с кучей Assign выражений
одно Assign выражение сетает конкретный проп если есть значение в словаре (а если его нет то мб сетает дефолт либо не меняет - это уже надо уточнять)
и уже построенный блок компилит

2018-08-15 08:46 UTC, KatzuoOgust approved these changes

2018-08-15 08:46 UTC, Happi-cat commented on ReadingList.Domain/Services/EntityUpdate/EntityUpdateService.cs
> +            if (_cache.TryGetValue(entityType, out var updater))
лучше использовать `GetOrAdd` https://msdn.microsoft.com/en-us/library/ee378677(v=vs.110).aspx
вместо  нескольких `TryGetValue`  и `TryAdd`
вопрос атомарности с точки зрения работы из разных потоков

2018-08-15 08:46 UTC, Happi-cat commented on ReadingList.Domain/Services/EntityUpdate/EntityUpdateService.cs
> +                p.CustomAttributes.All(a => a.AttributeType != typeof(IgnoreUpdateAttribute))).ToList();
можно проверить используя [экстеншон](https://msdn.microsoft.com/en-us/library/hh138307(v=vs.110).aspx): 
`p.GetCustomAttribute<IgnoreUpdateAttribute>(false) == null`

2018-08-15 08:46 UTC, Happi-cat commented on ReadingList.Domain/Services/EntityUpdate/EntityUpdateService.cs
> +                expressions.Add(Expression.IfThen(
можно использовать `yield return` вместо добавления в лист

2019-03-25 11:00 UTC, KatzuoOgust approved these changes

2019-03-25 14:37 UTC, merged